/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'IT000531' at '5/1/17 8:46 AM' with Gradle 2.14.1
 *
 * @author IT000531, @date 5/1/17 8:46 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
